/* eslint-disable @typescript-eslint/no-require-imports -- Optional standalone Node/Playwright runner. */
// Run after DB/auth suites, never concurrently with a database reset.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const {createClient}=require('@supabase/supabase-js');
const {execFileSync}=require('node:child_process');
const {randomUUID}=require('node:crypto');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const base=process.env.REVIEW_BASE_URL || 'http://localhost:3000';
if(!['localhost','127.0.0.1','[::1]'].includes(new URL(base).hostname))throw Error('Local preview only');
for(const marker of ['project-ref','remote-db-url','pooler-url']) {
 if(fs.existsSync(path.join(root,'supabase','.temp',marker)))throw Error('Refusing linked project');
}
const status=JSON.parse(execFileSync('npx',['--no-install','supabase','status','-o','json'],{cwd:root,encoding:'utf8',stdio:['ignore','pipe','pipe']}));
if(!['localhost','127.0.0.1','[::1]'].includes(new URL(status.API_URL).hostname))throw Error('Local database only');
const service=createClient(status.API_URL,status.SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const runId=randomUUID();
const people={};
let stage='preflight';
const check=(r)=>{if(r.error)throw Error(r.error.message);return r.data;};
(async()=>{
 for(const role of ['admin','owner','helper']) {
  const password='Review-'+randomUUID();
  const email=`${role}-${runId}@edison.example`;
  const user=check(await service.auth.admin.createUser({email,password,email_confirm:true})).user;
  check(await service.from('app_accounts').insert({id:user.id,email,display_name:`Review ${role}`,role:role==='admin'?'admin':'technician',status:'active'}));
  people[role]={id:user.id,email,password};
 }
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 const errors=[];
 const make=async()=>{const c=await browser.newContext({viewport:{width:1360,height:900}});const p=await c.newPage();p.setDefaultTimeout(15000);p.on('pageerror',()=>errors.push('Browser runtime error'));return p;};
 const card=(p,h)=>p.locator('.card').filter({has:p.getByRole('heading',{name:h,exact:true})});
 const login=async(p,role)=>{await p.goto(base+'/login');await p.getByLabel('Email',{exact:true}).fill(people[role].email);await p.getByLabel('Password',{exact:true}).fill(people[role].password);await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.getByRole('heading',{name:'Open Queue',exact:true}).waitFor();};
 try {
  const p=await make();
  await p.goto(base+'/my-tickets');assert(new URL(p.url()).pathname==='/login');
  stage='login';await login(p,'owner');assert.equal(await p.getByRole('button',{name:'Switch user',exact:true}).count(),0);
  await p.goto(base+'/admin');await p.waitForURL('**/queue');
  stage='intake';await p.goto(base+'/tickets/new');
  assert.equal(await p.locator('#owner-fixed').inputValue(),'Review owner');
  assert.equal(await p.locator('#channel-fixed').inputValue(),'Walk-in');
  await p.getByLabel('Requester',{exact:true}).selectOption('unknown');
  await p.getByLabel('Issue',{exact:true}).fill('Persisted review '+runId);
  await p.locator('#issue').fill('Synthetic browser regression request.');
  await p.getByRole('button',{name:'Create ticket',exact:true}).click();
  stage='detail';await card(p,'People').waitFor();const url=p.url();
  await card(p,'Work notes').getByLabel('Add a work note').fill('Verified cable; awaiting replacement.');
  await card(p,'Work notes').getByRole('button',{name:'Add note',exact:true}).click();
  await card(p,'Work notes').getByText('Verified cable; awaiting replacement.',{exact:true}).waitFor();
  stage='collaborators';await card(p,'People').getByLabel('Add a collaborator').selectOption(people.helper.id);
  await card(p,'People').getByRole('button',{name:'Add collaborator',exact:true}).click();
  await card(p,'People').locator('.person-row').filter({hasText:'Review helper'}).waitFor();
  await card(p,'People').getByRole('button',{name:'Return to Open Queue',exact:true}).click();
  await card(p,'People').getByRole('button',{name:'Claim',exact:true}).waitFor();
  await p.reload();await card(p,'Work notes').getByText('Verified cable; awaiting replacement.',{exact:true}).waitFor();
  stage='reclaim';const helper=await make();await login(helper,'helper');await helper.goto(url);
  await card(helper,'People').getByRole('button',{name:'Claim',exact:true}).click();
  await card(helper,'People').getByRole('button',{name:'Return to Open Queue',exact:true}).waitFor();
  await p.reload();assert.equal(await card(p,'Work notes').count(),0);
  stage='resolve';await card(helper,'Resolve').getByRole('button',{name:'Resolve ticket',exact:true}).click();
  await card(helper,'Resolve').getByText('A solution is required to resolve a ticket.',{exact:true}).waitFor();
  await card(helper,'Resolve').getByLabel('Solution',{exact:true}).fill('Replaced cable and verified normal display.');
  stage='resolve';await card(helper,'Resolve').getByRole('button',{name:'Resolve ticket',exact:true}).click();await card(helper,'Solution').waitFor();
  await helper.reload();assert.match(await card(helper,'Solution').innerText(),/No time was recorded/);
  await helper.setViewportSize({width:375,height:812});
  assert(await helper.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  fs.mkdirSync('/tmp/edison-m3-review',{recursive:true});await helper.screenshot({path:'/tmp/edison-m3-review/phone-detail.png',fullPage:true});
  stage='logout';await helper.getByRole('button',{name:'Sign out',exact:true}).click();await helper.waitForURL('**/login');
  await helper.goto(url);assert.equal(new URL(helper.url()).pathname,'/login');
  stage='admin provisioning';
  const adminPage=await make();await login(adminPage,'admin');await adminPage.goto(base+'/admin');
  const newName='Setup review '+runId;
  const newEmail='setup-'+runId+'@edison.example';
  await adminPage.getByLabel('Full name',{exact:true}).fill(newName);
  await adminPage.getByLabel('School email',{exact:true}).fill(newEmail);
  await adminPage.getByRole('button',{name:'Create account',exact:true}).click();
  const row=adminPage.locator('tbody tr').filter({hasText:newEmail});
  await row.getByRole('button',{name:'Issue setup link',exact:true}).waitFor();
  await row.getByRole('button',{name:'Issue setup link',exact:true}).click();
  const linkField=adminPage.getByLabel('Setup link for '+newName,{exact:true});
  await linkField.waitFor();
  const setupUrl=await linkField.inputValue();
  const recipient=await make();stage='setup callback';await recipient.goto(setupUrl);
  assert.equal(new URL(recipient.url()).origin,new URL(setupUrl).origin);
  await recipient.getByLabel('New app password',{exact:true}).waitFor();
  const newPassword='Setup-'+randomUUID();
  await recipient.getByLabel('New app password',{exact:true}).fill(newPassword);
  await recipient.getByLabel('Confirm app password',{exact:true}).fill(newPassword);
  stage='setup completion';await recipient.getByRole('button',{name:'Set password and activate',exact:true}).click();
  await recipient.waitForURL('**/login?setup=done');
  people.newTech={email:newEmail,password:newPassword};await login(recipient,'newTech');
  stage='recovery issuance';await adminPage.reload();
  await row.getByRole('button',{name:'Issue recovery link',exact:true}).click();await linkField.waitFor();
  const recoveryUrl=await linkField.inputValue();
  const recovery=await make();await recovery.goto(recoveryUrl);
  await recovery.getByLabel('New app password',{exact:true}).waitFor();
  const recoveredPassword='Recovered-'+randomUUID();
  await recovery.getByLabel('New app password',{exact:true}).fill(recoveredPassword);
  await recovery.getByLabel('Confirm app password',{exact:true}).fill(recoveredPassword);
  stage='recovery completion';await recovery.getByRole('button',{name:'Change password',exact:true}).click();
  await recovery.waitForURL('**/login?setup=recovered');
  await recipient.goto(base+'/queue');assert.notEqual(new URL(recipient.url()).pathname,'/queue');
  people.newTech.password=recoveredPassword;await login(recovery,'newTech');
  console.log('PASS admin account creation, real callback/setup, recovery completion and old-browser revocation');
  assert.deepEqual(errors,[]);
  console.log('PASS real login, protected routes, technician intake, persisted notes, collaborators, return/reclaim/access loss, resolution without time, refresh, phone layout, logout');
 } finally {await browser.close();}
})().catch((error)=>{let message=String(error.message).split('\n')[0].replace(/https?:\/\/\S+/g,'[URL]');for(const p of Object.values(people)){message=message.replaceAll(p.password,'[redacted]');}console.error(`M3 browser regression failed at ${stage}: ${message}`);process.exitCode=1;});
