-- Edison helpdesk — M2 core schema.
--
-- Mapping to the TypeScript domain in src/lib/domain/types.ts is snake_case here
-- and camelCase there; docs/M2-DATABASE.md carries the full column-by-column map.
-- Nothing in this file trusts client input: identity, role and time all come
-- from the database in later migrations. This file defines shape and invariants.
--
-- Calendar dates (ticket submission, work-log dates) are school-local
-- America/New_York dates, matching the M1 formatting rules. Real event instants
-- are timestamptz.

create extension if not exists pgcrypto with schema extensions;

-- School-local "today". STABLE, not IMMUTABLE, so it cannot appear in a CHECK
-- constraint; date-window rules are enforced by triggers and RPCs instead.
create or replace function public.app_today()
returns date
language sql
stable
set search_path = ''
as $$
  select ((now() at time zone 'America/New_York')::date);
$$;

comment on function public.app_today() is
  'School-local (America/New_York) current date used for submission and work-log date rules.';

-- ---------------------------------------------------------------------------
-- Accounts: login identities. One row per auth user.
-- ---------------------------------------------------------------------------

create table public.app_accounts (
  -- Shares the auth user id so auth.uid() is directly the account id.
  -- RESTRICT: deleting an auth user must never cascade away ticket history.
  id uuid primary key references auth.users (id) on delete restrict,
  display_name text not null,
  email text not null,
  role text not null default 'technician',
  -- New accounts start restricted until password setup completes (M3).
  status text not null default 'setup_pending',
  created_at timestamptz not null default now(),
  -- Records THAT an admin issued a setup/recovery link, never the link or token.
  last_credential_action_at timestamptz,
  last_credential_action_kind text,
  constraint app_accounts_display_name_present check (length(btrim(display_name)) between 1 and 120),
  constraint app_accounts_email_shape check (email = lower(btrim(email)) and email ~ '^[^\s@]+@[^\s@]+\.[^\s@]+$'),
  constraint app_accounts_email_unique unique (email),
  constraint app_accounts_role_valid check (role in ('admin', 'technician')),
  constraint app_accounts_status_valid check (status in ('active', 'inactive', 'setup_pending')),
  constraint app_accounts_credential_kind_valid check (
    last_credential_action_kind is null
    or last_credential_action_kind in ('setup_issued', 'recovery_issued')
  ),
  constraint app_accounts_credential_pairing check (
    (last_credential_action_at is null) = (last_credential_action_kind is null)
  )
);

comment on table public.app_accounts is
  'Helpdesk login identities. Role and status are server-controlled; never writable by the account holder.';

create index app_accounts_active_idx on public.app_accounts (status) where status = 'active';

-- ---------------------------------------------------------------------------
-- Requesters: the people who report faults. NOT login identities, and not a
-- student/staff directory — only the minimum a technician needs to do the job.
-- ---------------------------------------------------------------------------

create table public.requesters (
  id uuid primary key default extensions.gen_random_uuid(),
  display_name text not null,
  kind text not null default 'staff',
  descriptor text,
  created_at timestamptz not null default now(),
  created_by uuid not null references public.app_accounts (id) on delete restrict,
  constraint requesters_display_name_present check (length(btrim(display_name)) between 1 and 120),
  constraint requesters_kind_valid check (kind in ('staff', 'student', 'role', 'unknown')),
  constraint requesters_descriptor_shape check (descriptor is null or length(btrim(descriptor)) > 0)
);

comment on table public.requesters is
  'Minimal requester records for ticket intake. No login, no directory attributes beyond a label.';

-- ---------------------------------------------------------------------------
-- Tickets
-- ---------------------------------------------------------------------------

-- Readable ticket numbers are generated by the database, never by a client.
create sequence public.ticket_number_seq as bigint start with 1001 owned by none;

create table public.tickets (
  id uuid primary key default extensions.gen_random_uuid(),
  number text not null default ('EDT-' || nextval('public.ticket_number_seq')),
  title text not null,
  issue text not null,
  -- Either a known requester, or explicitly recorded as unknown. Never neither.
  requester_id uuid references public.requesters (id) on delete restrict,
  requester_unknown boolean not null default false,
  location text,
  is_remote boolean not null default false,
  channel text not null,
  priority text not null default 'normal',
  status text not null default 'open',
  -- School-local submission date. Admins may backdate; never a future date.
  submitted_on date not null,
  -- The real creation instant. Backdating submitted_on must never rewrite this.
  created_at timestamptz not null default now(),
  created_by uuid not null references public.app_accounts (id) on delete restrict,
  -- Primary owner. Preserved when a collaborator resolves.
  owner_id uuid references public.app_accounts (id) on delete restrict,
  assigned_at timestamptz,
  waiting_reason text,
  -- Survives a reopen as the "previous solution"; cleared only by a new resolve.
  solution text,
  -- Resolver is recorded separately from the owner.
  resolved_by uuid references public.app_accounts (id) on delete restrict,
  resolved_at timestamptz,
  cancel_reason text,

  constraint tickets_number_unique unique (number),
  constraint tickets_title_length check (length(btrim(title)) between 1 and 120),
  constraint tickets_issue_present check (length(btrim(issue)) > 0),
  constraint tickets_channel_valid check (channel in ('walk_in', 'email', 'phone_call')),
  constraint tickets_priority_valid check (priority in ('low', 'normal', 'high', 'urgent')),
  constraint tickets_status_valid check (
    status in ('open', 'assigned', 'in_progress', 'waiting', 'resolved', 'cancelled')
  ),
  -- Unknown requester and unknown location must both stay representable.
  constraint tickets_requester_resolution check (
    (requester_unknown and requester_id is null)
    or (not requester_unknown and requester_id is not null)
  ),
  constraint tickets_location_shape check (
    (is_remote and location is null)
    or (not is_remote and (location is null or length(btrim(location)) > 0))
  ),
  -- Lifecycle invariants.
  constraint tickets_open_has_no_owner check (
    status <> 'open' or (owner_id is null and assigned_at is null)
  ),
  constraint tickets_active_owned_has_owner check (
    status not in ('assigned', 'in_progress', 'waiting')
    or (owner_id is not null and assigned_at is not null)
  ),
  constraint tickets_waiting_has_reason check (
    (status = 'waiting') = (waiting_reason is not null)
  ),
  constraint tickets_waiting_reason_present check (
    waiting_reason is null or length(btrim(waiting_reason)) > 0
  ),
  -- A resolution needs a meaningful solution, a resolver, and a timestamp.
  constraint tickets_resolved_complete check (
    status <> 'resolved'
    or (
      solution is not null
      and length(btrim(solution)) >= 5
      and resolved_by is not null
      and resolved_at is not null
    )
  ),
  -- Reopening clears resolver/resolved_at but keeps the previous solution text.
  constraint tickets_unresolved_has_no_resolver check (
    status = 'resolved' or (resolved_by is null and resolved_at is null)
  ),
  -- Cancelling is never a resolution.
  constraint tickets_cancelled_has_reason check (
    (status = 'cancelled') = (cancel_reason is not null)
  ),
  constraint tickets_cancel_reason_present check (
    cancel_reason is null or length(btrim(cancel_reason)) > 0
  ),
  constraint tickets_assigned_at_pairs_owner check (
    (owner_id is null and assigned_at is null)
    or (owner_id is not null and assigned_at is not null)
    or status in ('resolved', 'cancelled')
  )
);

comment on table public.tickets is
  'One row per request. Queues are filtered views of this table, never separate copies.';
comment on column public.tickets.created_at is
  'Real creation instant, immutable. Backdating writes submitted_on only.';
comment on column public.tickets.solution is
  'Current or previous solution. Retained through a reopen so history is not lost.';

-- Queue, ownership and history access paths.
create index tickets_open_queue_idx on public.tickets (priority, created_at)
  where status = 'open' and owner_id is null;
create index tickets_owner_idx on public.tickets (owner_id, status);
create index tickets_status_idx on public.tickets (status);
create index tickets_submitted_on_idx on public.tickets (submitted_on);
create index tickets_resolved_at_idx on public.tickets (resolved_at desc) where resolved_at is not null;

-- ---------------------------------------------------------------------------
-- Collaborators: one row per participating technician, never a joined string.
-- ---------------------------------------------------------------------------

create table public.ticket_collaborators (
  ticket_id uuid not null references public.tickets (id) on delete cascade,
  account_id uuid not null references public.app_accounts (id) on delete restrict,
  added_by uuid not null references public.app_accounts (id) on delete restrict,
  added_at timestamptz not null default now(),
  -- Primary key also prevents duplicate collaborator rows.
  primary key (ticket_id, account_id)
);

create index ticket_collaborators_account_idx on public.ticket_collaborators (account_id);

-- ---------------------------------------------------------------------------
-- Contributions
-- ---------------------------------------------------------------------------

create table public.device_observations (
  id uuid primary key default extensions.gen_random_uuid(),
  ticket_id uuid not null references public.tickets (id) on delete cascade,
  device_type text not null,
  model text,
  os_version text,
  -- Unknown serial/asset tag must never block recording a device.
  serial_number text,
  asset_tag text,
  identifiers_not_applicable boolean not null default false,
  recorded_by uuid not null references public.app_accounts (id) on delete restrict,
  recorded_at timestamptz not null default now(),
  constraint device_observations_type_present check (length(btrim(device_type)) between 1 and 120)
);

create index device_observations_ticket_idx on public.device_observations (ticket_id);

create table public.notes (
  id uuid primary key default extensions.gen_random_uuid(),
  ticket_id uuid not null references public.tickets (id) on delete cascade,
  author_id uuid not null references public.app_accounts (id) on delete restrict,
  body text not null,
  created_at timestamptz not null default now(),
  constraint notes_body_present check (length(btrim(body)) > 0)
);

create index notes_ticket_idx on public.notes (ticket_id, created_at);

-- Optional per-person time. Absent rows mean "not recorded", which is
-- deliberately different from a recorded zero, so zero minutes is rejected.
create table public.work_logs (
  id uuid primary key default extensions.gen_random_uuid(),
  ticket_id uuid not null references public.tickets (id) on delete cascade,
  contributor_id uuid not null references public.app_accounts (id) on delete restrict,
  work_date date not null,
  minutes integer not null,
  description text,
  created_at timestamptz not null default now(),
  constraint work_logs_minutes_range check (minutes > 0 and minutes <= 1440)
);

create index work_logs_ticket_idx on public.work_logs (ticket_id);
create index work_logs_contributor_idx on public.work_logs (contributor_id);

-- Append-only audit trail. Written in the same transaction as its mutation.
create table public.activity_events (
  id uuid primary key default extensions.gen_random_uuid(),
  ticket_id uuid not null references public.tickets (id) on delete cascade,
  kind text not null,
  actor_id uuid not null references public.app_accounts (id) on delete restrict,
  at timestamptz not null default now(),
  summary text not null,
  detail text,
  constraint activity_events_kind_valid check (
    kind in (
      'created', 'claimed', 'assigned', 'returned_to_queue',
      'collaborator_added', 'collaborator_removed', 'note_added',
      'device_recorded', 'priority_changed', 'status_changed',
      'time_logged', 'resolved', 'reopened', 'cancelled'
    )
  ),
  constraint activity_events_summary_present check (length(btrim(summary)) > 0)
);

create index activity_events_ticket_idx on public.activity_events (ticket_id, at);

comment on table public.activity_events is
  'Append-only history. Never holds a credential, setup link, or recovery token.';
