-- ---------------------------------------------------------------------------
-- Forms: the sign-up sheet, the permission slip and the check-in, kept against
-- the directory instead of beside it.
--
-- A skills officer running a trip does this today: a Google Form, a Google
-- Sheet behind it, and an afternoon of copying names out of one and into a
-- roster, matching "Jordan R." to an OSIS by hand. Every respondent retypes
-- facts the school already holds — their own name, their class, their
-- guardian's phone — and half of them get one of those wrong.
--
-- This is that form, with three differences that are the whole point:
--
--   * A DIRECTORY FIELD is a question the directory already knows the answer
--     to. The respondent proves who they are once (school email AND OSIS or
--     staff id, both on the same record) and those questions arrive filled in,
--     editable, so a guardian's new number is a correction rather than a
--     retype. What they change is recorded as changed, so the officer can see
--     which answers disagree with the directory.
--   * A LINKED GROUP turns a matched response into a roster row: the trip's
--     sign-up form fills the trip's roster. A LINKED EVENT marks the matched
--     respondent present, which is what a check-in form is.
--   * The PUBLIC LINK is `/f/<slug>`, reached by somebody with no account at
--     all. Everything it can do goes through the four `app_public_form*`
--     functions below, granted to `anon`; `anon` holds no privilege on any
--     table here, and those functions answer as little as the page needs.
--
-- WHAT THE PUBLIC NEVER SEES. A guardian's phone number is never returned to
-- an anonymous caller, not even to the respondent it belongs to: the prefill
-- carries it masked to its last four digits ("••• ••• 1234"), and a respondent
-- who keeps it sends back "keep", which the database resolves to the number on
-- file. An address is never read at all. The identity check says the same
-- thing — "no match" — whether the email was wrong, the id was wrong or both,
-- so it cannot be used to learn which addresses are real.
--
-- ABUSE. The slug is 12 characters from a 31-letter alphabet, about 59 bits,
-- generated here and never chosen by a person, so a form cannot be found by
-- guessing. Failed identity checks are counted per form, per caller and per
-- form overall, and past either ceiling the form stops answering identity
-- questions for fifteen minutes. The caller key is a SHA-256 of the client
-- address the application server forwards (`x-edison-client`), or of the first
-- `x-forwarded-for` hop; it is never stored in the clear. A caller who forges
-- that header only moves between per-caller buckets — the per-form ceiling
-- holds regardless, and it is the one that bounds a brute force. Payloads are
-- capped (200 KB of answers, 60 questions, a signature of 20,000 characters),
-- and a closed or full form refuses a new response in the database, not only
-- on the page.
--
-- WHO MAY DO WHAT. Any active account may make a form: the skills officer is
-- the main audience, and a form that needed an administrator would be a Google
-- Form again by Friday. A form is SHARED by default, which means every active
-- account can see it, edit it and read its responses — the same openness a
-- group has. Its maker may unshare it, and then only the maker and an
-- administrator can reach it. Deleting a form and changing who sees it are the
-- maker's (or an administrator's), because those are the two acts somebody else
-- cannot undo for them.
--
-- NO DIRECT WRITES. Row-level security with SELECT policies only, SELECT
-- granted to `authenticated` and nothing to `anon`, and every change through a
-- SECURITY DEFINER function that re-derives the actor — or, for the public
-- functions, that re-checks the respondent's identity on every call.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- Forms are a seventh thing the record history can be about.
-- ---------------------------------------------------------------------------

alter table public.record_events
  drop constraint if exists record_events_entity_type_valid;

alter table public.record_events
  add constraint record_events_entity_type_valid check (
    entity_type in ('requester', 'inventory_device', 'invite', 'import', 'account', 'group', 'form')
  );

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.forms (
  id uuid primary key default extensions.gen_random_uuid(),
  -- The public address. Generated by app_form_slug(), never typed: a slug a
  -- person chose is a slug a person can guess.
  slug text not null unique check (slug ~ '^[a-z0-9]{12}$'),
  title text not null check (pg_catalog.length(pg_catalog.btrim(title)) between 1 and 120),
  description text not null default '' check (pg_catalog.length(description) <= 2000),
  -- The questions, in order, as app_form_clean_fields() leaves them. One
  -- document rather than a child table because the builder saves the whole
  -- form at once and a response is read against the whole list.
  fields jsonb not null default '[]'::jsonb check (pg_catalog.jsonb_typeof(fields) = 'array'),
  is_open boolean not null default true,
  closes_at timestamptz,
  response_cap integer check (response_cap is null or response_cap between 1 and 10000),
  audience text not null default 'directory' check (audience in ('directory', 'anyone')),
  -- SET NULL on both: a trip roster that is deleted does not take the sign-up
  -- form with it, it simply stops filling a roster.
  group_id uuid references public.people_groups (id) on delete set null,
  event_id uuid references public.group_events (id) on delete set null,
  shared boolean not null default true,
  created_by uuid references public.app_accounts (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.forms is
  'A form: questions, some of them answered from the directory, reached publicly at /f/<slug> or at a signed-in kiosk. Written only by the app_*form* functions.';
comment on column public.forms.fields is
  'Ordered questions: {id, type, label, help, required, options?, directory?}. Types: short_text, long_text, single_choice, multi_choice, dropdown, number, date, yes_no, signature, directory. Cleaned by app_form_clean_fields().';
comment on column public.forms.audience is
  'directory: a respondent proves who they are with school email and OSIS or staff id before answering. anyone: no identity step; responses are anonymous unless taken at a kiosk.';
comment on column public.forms.shared is
  'Whether every active account can see and edit the form and read its responses. When false, only its maker and administrators can.';

create index if not exists forms_updated_idx on public.forms (updated_at desc);

create table if not exists public.form_responses (
  id uuid primary key default extensions.gen_random_uuid(),
  form_id uuid not null references public.forms (id) on delete cascade,
  -- SET NULL: the answers outlive a directory record that is removed, and the
  -- screen shows them as unmatched rather than losing them.
  requester_id uuid references public.requesters (id) on delete set null,
  answers jsonb not null default '{}'::jsonb check (pg_catalog.jsonb_typeof(answers) = 'object'),
  -- The directory questions whose answer the respondent changed from what
  -- the directory holds. A list of question ids.
  changed text[] not null default '{}',
  via text not null check (via in ('link', 'kiosk')),
  -- The signed-in account whose kiosk took the response. NULL for the link.
  recorded_by uuid references public.app_accounts (id),
  submitted_at timestamptz not null default now()
);

comment on table public.form_responses is
  'One response to one form. A directory-matched respondent has at most one per form: answering again replaces their earlier answers. Written only by the submit functions and deleted only by app_delete_form_response.';

create index if not exists form_responses_form_idx
  on public.form_responses (form_id, submitted_at desc);

-- One response per person per form. Answering again is a correction, not a
-- second sign-up, and a roster built from a form must not list anybody twice.
create unique index if not exists form_responses_one_per_person
  on public.form_responses (form_id, requester_id)
  where requester_id is not null;

create index if not exists form_responses_requester_idx
  on public.form_responses (requester_id);

/*
 * The throttle's memory. `kind` is 'miss' for an identity check that matched
 * nobody and 'submit' for a response to an open (`anyone`) form. Rows older
 * than a day are pruned by the next identity check on the same form, so this
 * table is a sliding window, not a log.
 */
create table if not exists public.form_identity_attempts (
  form_id uuid not null references public.forms (id) on delete cascade,
  client_key text not null,
  kind text not null check (kind in ('miss', 'submit')),
  at timestamptz not null default now()
);

comment on table public.form_identity_attempts is
  'Recent failed identity checks and open-form submissions, per form and per hashed client address, for the public throttle. Never readable by any client role.';

create index if not exists form_identity_attempts_idx
  on public.form_identity_attempts (form_id, kind, at);

-- ---------------------------------------------------------------------------
-- Internal helpers. Reachable by no client role.
-- ---------------------------------------------------------------------------

create or replace function public.app_form_slug()
returns text
language plpgsql
volatile
set search_path = ''
as $$
declare
  -- No 0/o, 1/l/i: a slug is read off a poster and typed into a phone.
  v_alphabet constant text := 'abcdefghjkmnpqrstuvwxyz23456789';
  v_bytes bytea := extensions.gen_random_bytes(12);
  v_slug text := '';
  i integer;
begin
  for i in 0..11 loop
    v_slug := v_slug || pg_catalog.substr(v_alphabet, (pg_catalog.get_byte(v_bytes, i) % 31) + 1, 1);
  end loop;
  return v_slug;
end;
$$;

create or replace function public.app_form_can_see(p_form public.forms)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.app_active_account_id() is not null
    and (
      p_form.shared
      or p_form.created_by = public.app_active_account_id()
      or public.app_is_admin()
    );
$$;

create or replace function public.app_form_can_own(p_form public.forms)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.app_active_account_id() is not null
    and (p_form.created_by = public.app_active_account_id() or public.app_is_admin());
$$;

/*
 * Whether a form takes a new response right now: 'open', 'closed' or 'full'.
 * Closed wins over full, because "this form is closed" is the truer sentence
 * when both are so.
 */
create or replace function public.app_form_state(p_form public.forms)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when not p_form.is_open then 'closed'
    when p_form.closes_at is not null and p_form.closes_at <= pg_catalog.now() then 'closed'
    when p_form.response_cap is not null
      and (select pg_catalog.count(*) from public.form_responses r where r.form_id = p_form.id)
        >= p_form.response_cap then 'full'
    else 'open'
  end;
$$;

/*
 * The questions, as a caller sent them, made safe to store.
 *
 * Refuses with a sentence anything that would make a form unanswerable or
 * unreadable — an unknown type, two questions with one id, the same directory
 * fact asked twice — and quietly tidies what is merely untidy: blank and
 * repeated choices are dropped, help text is cut at 500 characters. An empty
 * label is allowed, because the builder saves while somebody is still typing;
 * the page calls such a question "Untitled question".
 */
create or replace function public.app_form_clean_fields(p_fields jsonb)
returns jsonb
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_out jsonb := '[]'::jsonb;
  v_field jsonb;
  v_id text;
  v_type text;
  v_label text;
  v_help text;
  v_required boolean;
  v_options jsonb;
  v_clean jsonb;
  v_option jsonb;
  v_text text;
  v_directory text;
  v_ids text[] := '{}';
  v_directories text[] := '{}';
  v_at integer := 0;
begin
  if p_fields is null then
    return '[]'::jsonb;
  end if;
  if pg_catalog.jsonb_typeof(p_fields) <> 'array' then
    raise exception 'Send the questions as a list.' using errcode = 'check_violation';
  end if;
  if pg_catalog.jsonb_array_length(p_fields) > 60 then
    raise exception 'A form has 60 questions at most.' using errcode = 'check_violation';
  end if;

  for v_field in select e.value from pg_catalog.jsonb_array_elements(p_fields) e loop
    v_at := v_at + 1;
    if pg_catalog.jsonb_typeof(v_field) <> 'object' then
      raise exception 'Question % is not a question.', v_at using errcode = 'check_violation';
    end if;

    v_id := coalesce(v_field ->> 'id', '');
    if v_id !~ '^[a-z0-9]{1,16}$' then
      raise exception 'Question % has no usable id.', v_at using errcode = 'check_violation';
    end if;
    if v_id = any(v_ids) then
      raise exception 'Two questions share the id %.', v_id using errcode = 'check_violation';
    end if;

    v_type := coalesce(v_field ->> 'type', '');
    if v_type not in (
      'short_text', 'long_text', 'single_choice', 'multi_choice', 'dropdown',
      'number', 'date', 'yes_no', 'signature', 'directory'
    ) then
      raise exception 'Question % has a type this form does not know.', v_at
        using errcode = 'check_violation';
    end if;

    v_label := pg_catalog.btrim(coalesce(v_field ->> 'label', ''));
    if pg_catalog.length(v_label) > 200 then
      raise exception 'A question is 200 characters at most.' using errcode = 'check_violation';
    end if;
    v_help := pg_catalog.left(pg_catalog.btrim(coalesce(v_field ->> 'help', '')), 500);
    v_required := case
      when pg_catalog.jsonb_typeof(v_field -> 'required') = 'boolean'
        then (v_field ->> 'required')::boolean
      else false
    end;

    v_clean := null;
    if v_type in ('single_choice', 'multi_choice', 'dropdown') then
      v_options := coalesce(v_field -> 'options', '[]'::jsonb);
      if pg_catalog.jsonb_typeof(v_options) <> 'array' then
        raise exception 'Question % needs its choices as a list.', v_at using errcode = 'check_violation';
      end if;
      if pg_catalog.jsonb_array_length(v_options) > 50 then
        raise exception 'A question has 50 choices at most.' using errcode = 'check_violation';
      end if;
      v_clean := '[]'::jsonb;
      for v_option in select o.value from pg_catalog.jsonb_array_elements(v_options) o loop
        if pg_catalog.jsonb_typeof(v_option) <> 'string' then
          continue;
        end if;
        v_text := pg_catalog.btrim(v_option #>> '{}');
        if v_text = '' or v_clean ? v_text then
          continue;
        end if;
        if pg_catalog.length(v_text) > 120 then
          raise exception 'A choice is 120 characters at most.' using errcode = 'check_violation';
        end if;
        v_clean := v_clean || pg_catalog.jsonb_build_array(v_text);
      end loop;
    end if;

    v_directory := null;
    if v_type = 'directory' then
      v_directory := coalesce(v_field ->> 'directory', '');
      if v_directory not in (
        'full_name', 'external_id', 'email', 'class_of', 'official_class',
        'guardian_name', 'guardian_phone'
      ) then
        raise exception 'Question % asks the directory for something it does not hold.', v_at
          using errcode = 'check_violation';
      end if;
      if v_directory = any(v_directories) then
        raise exception 'The form already asks for that from the directory.'
          using errcode = 'check_violation';
      end if;
      v_directories := v_directories || v_directory;
    end if;

    v_ids := v_ids || v_id;
    v_out := v_out || pg_catalog.jsonb_build_array(pg_catalog.jsonb_strip_nulls(pg_catalog.jsonb_build_object(
      'id', v_id,
      'type', v_type,
      'label', v_label,
      'help', v_help,
      'required', v_required,
      'options', v_clean,
      'directory', v_directory
    )));
  end loop;

  return v_out;
end;
$$;

/* One directory fact, as a form asks for it. */
create or replace function public.app_form_directory_value(p_person public.requesters, p_key text)
returns text
language sql
stable
set search_path = ''
as $$
  select nullif(pg_catalog.btrim(coalesce(case p_key
    when 'full_name' then p_person.display_name
    when 'external_id' then p_person.external_id
    when 'email' then p_person.email
    when 'class_of' then p_person.class_of
    when 'official_class' then p_person.official_class
    when 'guardian_name' then p_person.guardian_name
    when 'guardian_phone' then p_person.guardian_phone
  end, '')), '');
$$;

/*
 * What a matched respondent sees filled in: the directory's answer to every
 * directory question on THIS form and nothing else, with the guardian's phone
 * masked to its last four digits. Nothing the form does not ask for leaves the
 * database, and the phone never leaves it whole.
 */
create or replace function public.app_form_prefill(p_form public.forms, p_person public.requesters)
returns jsonb
language plpgsql
stable
set search_path = ''
as $$
declare
  v_prefill jsonb := '{}'::jsonb;
  v_masked jsonb := '{}'::jsonb;
  v_field jsonb;
  v_value text;
  v_digits text;
begin
  for v_field in
    select e.value from pg_catalog.jsonb_array_elements(p_form.fields) e
    where e.value ->> 'type' = 'directory'
  loop
    if v_field ->> 'directory' = 'guardian_phone' then
      v_digits := pg_catalog.regexp_replace(coalesce(p_person.guardian_phone, ''), '\D', '', 'g');
      if pg_catalog.length(v_digits) >= 4 then
        v_masked := v_masked || pg_catalog.jsonb_build_object(
          v_field ->> 'id',
          '••• ••• ' || pg_catalog.right(v_digits, 4)
        );
      end if;
      continue;
    end if;

    v_value := public.app_form_directory_value(p_person, v_field ->> 'directory');
    if v_value is not null then
      v_prefill := v_prefill || pg_catalog.jsonb_build_object(v_field ->> 'id', v_value);
    end if;
  end loop;

  return pg_catalog.jsonb_build_object('prefill', v_prefill, 'masked', v_masked);
end;
$$;

/* "Jordan", for the greeting. The first name, or the first word of the name. */
create or replace function public.app_form_first_name(p_person public.requesters)
returns text
language sql
stable
set search_path = ''
as $$
  select coalesce(
    nullif(pg_catalog.btrim(coalesce(p_person.first_name, '')), ''),
    pg_catalog.split_part(pg_catalog.btrim(coalesce(p_person.display_name, '')), ' ', 1)
  );
$$;

/*
 * The answers, as a respondent sent them, checked against the questions.
 *
 * Answers to questions the form does not ask are dropped. Every answer is
 * checked against its type — a choice has to be one of the choices, a date a
 * real date, a number a number — and a required question left empty refuses
 * the whole response with a sentence naming it. A directory question answered
 * `{"keep": true}` takes the directory's own value, which is how a masked phone
 * number is kept without ever having been shown; one answered with text that
 * differs from the directory is listed in `changed`.
 *
 * Returns {answers: {...}, changed: [...]}.
 */
create or replace function public.app_form_clean_answers(
  p_form public.forms,
  p_answers jsonb,
  p_person public.requesters
)
returns jsonb
language plpgsql
stable
set search_path = ''
as $$
declare
  v_answers jsonb := '{}'::jsonb;
  v_changed jsonb := '[]'::jsonb;
  v_given jsonb;
  v_field jsonb;
  v_id text;
  v_type text;
  v_label text;
  v_raw jsonb;
  v_text text;
  v_value jsonb;
  v_directory text;
  v_limit integer;
  v_date date;
begin
  v_given := coalesce(p_answers, '{}'::jsonb);
  if pg_catalog.jsonb_typeof(v_given) <> 'object' then
    raise exception 'Send the answers as an object.' using errcode = 'check_violation';
  end if;
  if pg_catalog.length(v_given::text) > 200000 then
    raise exception 'Those answers are too long to take.' using errcode = 'check_violation';
  end if;

  for v_field in select e.value from pg_catalog.jsonb_array_elements(p_form.fields) e loop
    v_id := v_field ->> 'id';
    v_type := v_field ->> 'type';
    v_label := coalesce(nullif(v_field ->> 'label', ''), 'Untitled question');
    v_raw := v_given -> v_id;
    if v_raw is not null and pg_catalog.jsonb_typeof(v_raw) = 'null' then
      v_raw := null;
    end if;
    v_value := null;

    if v_type = 'directory' then
      v_directory := case
        when p_person.id is not null
          then public.app_form_directory_value(p_person, v_field ->> 'directory')
      end;
      if v_raw is null then
        v_text := null;
      elsif pg_catalog.jsonb_typeof(v_raw) = 'object' and (v_raw ->> 'keep') = 'true' then
        v_text := v_directory;
      elsif pg_catalog.jsonb_typeof(v_raw) = 'string' then
        v_text := pg_catalog.btrim(v_raw #>> '{}');
        if pg_catalog.length(v_text) > 300 then
          raise exception '"%" is 300 characters at most.', v_label using errcode = 'check_violation';
        end if;
        if v_directory is not null and v_text <> '' and (
          case when v_field ->> 'directory' = 'guardian_phone'
            then pg_catalog.regexp_replace(v_text, '\D', '', 'g')
              <> pg_catalog.regexp_replace(v_directory, '\D', '', 'g')
            else pg_catalog.lower(v_text) <> pg_catalog.lower(v_directory)
          end
        ) then
          v_changed := v_changed || pg_catalog.jsonb_build_array(v_id);
        end if;
      else
        raise exception 'Answer "%" with text.', v_label using errcode = 'check_violation';
      end if;
      if nullif(v_text, '') is not null then
        v_value := pg_catalog.to_jsonb(v_text);
      end if;

    elsif v_type in ('short_text', 'long_text') then
      if v_raw is not null then
        if pg_catalog.jsonb_typeof(v_raw) <> 'string' then
          raise exception 'Answer "%" with text.', v_label using errcode = 'check_violation';
        end if;
        v_text := pg_catalog.btrim(v_raw #>> '{}');
        v_limit := case when v_type = 'short_text' then 500 else 5000 end;
        if pg_catalog.length(v_text) > v_limit then
          raise exception '"%" is % characters at most.', v_label, v_limit using errcode = 'check_violation';
        end if;
        if v_text <> '' then
          v_value := pg_catalog.to_jsonb(v_text);
        end if;
      end if;

    elsif v_type = 'number' then
      if v_raw is not null then
        v_text := pg_catalog.btrim(v_raw #>> '{}');
        if v_text <> '' then
          if v_text !~ '^-?[0-9]{1,12}(\.[0-9]{1,6})?$' then
            raise exception 'Answer "%" with a number.', v_label using errcode = 'check_violation';
          end if;
          v_value := pg_catalog.to_jsonb(v_text::numeric);
        end if;
      end if;

    elsif v_type = 'date' then
      if v_raw is not null then
        v_text := pg_catalog.btrim(v_raw #>> '{}');
        if v_text <> '' then
          if v_text !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' then
            raise exception 'Answer "%" with a real date.', v_label using errcode = 'check_violation';
          end if;
          -- The cast is the calendar: 2026-02-30 is refused by it, and the
          -- refusal is turned into the sentence rather than a SQL error.
          begin
            v_date := v_text::date;
          exception
            when others then
              raise exception 'Answer "%" with a real date.', v_label using errcode = 'check_violation';
          end;
          v_value := pg_catalog.to_jsonb(v_text);
        end if;
      end if;

    elsif v_type = 'yes_no' then
      if v_raw is not null then
        if pg_catalog.jsonb_typeof(v_raw) = 'boolean' then
          v_value := v_raw;
        elsif pg_catalog.lower(v_raw #>> '{}') in ('yes', 'true') then
          v_value := 'true'::jsonb;
        elsif pg_catalog.lower(v_raw #>> '{}') in ('no', 'false') then
          v_value := 'false'::jsonb;
        elsif pg_catalog.btrim(v_raw #>> '{}') <> '' then
          raise exception 'Answer "%" with yes or no.', v_label using errcode = 'check_violation';
        end if;
      end if;

    elsif v_type in ('single_choice', 'dropdown') then
      if v_raw is not null then
        v_text := pg_catalog.btrim(v_raw #>> '{}');
        if v_text <> '' then
          if pg_catalog.jsonb_typeof(v_raw) <> 'string'
             or not (coalesce(v_field -> 'options', '[]'::jsonb) ? v_text) then
            raise exception 'Choose one of the choices for "%".', v_label using errcode = 'check_violation';
          end if;
          v_value := pg_catalog.to_jsonb(v_text);
        end if;
      end if;

    elsif v_type = 'multi_choice' then
      if v_raw is not null then
        if pg_catalog.jsonb_typeof(v_raw) <> 'array' or exists (
          select 1 from pg_catalog.jsonb_array_elements(v_raw) c
          where pg_catalog.jsonb_typeof(c.value) <> 'string'
             or not (coalesce(v_field -> 'options', '[]'::jsonb) ? (c.value #>> '{}'))
        ) then
          raise exception 'Choose from the choices for "%".', v_label using errcode = 'check_violation';
        end if;
        -- Kept in the order the form lists them, whatever order they arrived in.
        select pg_catalog.jsonb_agg(o.value order by o.ordinality)
        into v_value
        from pg_catalog.jsonb_array_elements_text(coalesce(v_field -> 'options', '[]'::jsonb))
          with ordinality as o(value, ordinality)
        where v_raw ? o.value;
      end if;

    elsif v_type = 'signature' then
      if v_raw is not null then
        v_text := pg_catalog.btrim(v_raw #>> '{}');
        if v_text <> '' then
          if pg_catalog.jsonb_typeof(v_raw) <> 'string'
             or pg_catalog.length(v_text) > 20000
             or v_text !~ '^[ML0-9 .-]+$' then
            raise exception 'That signature could not be read. Clear it and sign again.'
              using errcode = 'check_violation';
          end if;
          v_value := pg_catalog.to_jsonb(v_text);
        end if;
      end if;
    end if;

    if v_value is null then
      if coalesce((v_field ->> 'required')::boolean, false) then
        raise exception 'Answer "%".', v_label using errcode = 'check_violation';
      end if;
    else
      v_answers := v_answers || pg_catalog.jsonb_build_object(v_id, v_value);
    end if;
  end loop;

  return pg_catalog.jsonb_build_object('answers', v_answers, 'changed', v_changed);
end;
$$;

/*
 * Stores one response and does what the form is linked to.
 *
 * A matched person who has answered before has their answers replaced rather
 * than a second row added. A linked group gains them as a member; a linked
 * event marks them present. Both are "already true is not an error", exactly
 * as the group screens treat them.
 */
create or replace function public.app_form_record_response(
  p_form public.forms,
  p_person uuid,
  p_clean jsonb,
  p_via text,
  p_by uuid
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_existing uuid;
  v_id uuid;
  v_updated boolean := false;
  v_changed text[];
begin
  v_changed := array(select pg_catalog.jsonb_array_elements_text(coalesce(p_clean -> 'changed', '[]'::jsonb)));

  if p_person is not null then
    select r.id into v_existing
    from public.form_responses r
    where r.form_id = p_form.id and r.requester_id = p_person
    for update;
  end if;

  if v_existing is not null then
    update public.form_responses r
    set answers = p_clean -> 'answers',
        changed = v_changed,
        via = p_via,
        recorded_by = p_by,
        submitted_at = pg_catalog.now()
    where r.id = v_existing;
    v_id := v_existing;
    v_updated := true;
  else
    insert into public.form_responses (form_id, requester_id, answers, changed, via, recorded_by)
    values (p_form.id, p_person, p_clean -> 'answers', v_changed, p_via, p_by)
    returning id into v_id;
  end if;

  if p_person is not null and p_form.group_id is not null then
    insert into public.people_group_members (group_id, requester_id, added_by)
    values (p_form.group_id, p_person, p_by)
    on conflict do nothing;
    if found then
      update public.people_groups g set updated_at = pg_catalog.now() where g.id = p_form.group_id;
    end if;
  end if;

  if p_person is not null and p_form.event_id is not null then
    -- The membership is still the authority: somebody is marked present only
    -- at an event of a group they are in. With the form linked to the event's
    -- own group, the insert above has just made that true.
    if exists (
      select 1
      from public.group_events e
      join public.people_group_members m on m.group_id = e.group_id and m.requester_id = p_person
      where e.id = p_form.event_id
    ) then
      insert into public.group_attendance (event_id, requester_id, marked_by)
      values (p_form.event_id, p_person, p_by)
      on conflict do nothing;
    end if;
  end if;

  return pg_catalog.jsonb_build_object('id', v_id, 'updated', v_updated);
end;
$$;

/* The caller, as a hash: the forwarded client address, never stored whole. */
create or replace function public.app_form_client_key()
returns text
language sql
stable
set search_path = ''
as $$
  select pg_catalog.encode(extensions.digest(coalesce(
    nullif(pg_catalog.left(pg_catalog.btrim(public.app_request_headers() ->> 'x-edison-client'), 200), ''),
    nullif(pg_catalog.btrim(pg_catalog.split_part(public.app_request_headers() ->> 'x-forwarded-for', ',', 1)), ''),
    'unknown'
  ), 'sha256'), 'hex');
$$;

/*
 * Whether this caller, or this form as a whole, has run out of tries for the
 * next fifteen minutes. Ten wrong identities per caller and 150 per form;
 * thirty open-form responses per caller and 600 per form.
 */
create or replace function public.app_form_throttled(p_form uuid, p_key text, p_kind text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    (
      select pg_catalog.count(*)
      from public.form_identity_attempts a
      where a.form_id = p_form and a.kind = p_kind and a.client_key = p_key
        and a.at > pg_catalog.now() - interval '15 minutes'
    ) >= case when p_kind = 'miss' then 10 else 30 end
    or (
      select pg_catalog.count(*)
      from public.form_identity_attempts a
      where a.form_id = p_form and a.kind = p_kind
        and a.at > pg_catalog.now() - interval '15 minutes'
    ) >= case when p_kind = 'miss' then 150 else 600 end;
$$;

/*
 * The one person an email and an id both name, or nobody.
 *
 * Both have to match the SAME record, and the answer is the same NULL whether
 * neither, one or the other matched. Archived people are not matched: somebody
 * who has left is not signing up for next month's trip.
 */
create or replace function public.app_form_match_identity(p_email text, p_external_id text)
returns uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_email text := pg_catalog.lower(pg_catalog.btrim(coalesce(p_email, '')));
  v_id text := pg_catalog.lower(pg_catalog.regexp_replace(coalesce(p_external_id, ''), '\s', '', 'g'));
  v_count integer;
  v_match uuid;
begin
  if v_email = '' or v_id = '' or pg_catalog.length(v_email) > 320 or pg_catalog.length(v_id) > 80 then
    return null;
  end if;

  select pg_catalog.count(*)::integer, (pg_catalog.array_agg(r.id))[1]
  into v_count, v_match
  from public.requesters r
  where r.kind in ('student', 'staff')
    and r.archived_at is null
    and r.email is not null
    and pg_catalog.lower(r.email) = v_email
    and pg_catalog.lower(coalesce(r.external_id, '')) = v_id;

  if v_count = 1 then
    return v_match;
  end if;
  return null;
end;
$$;

-- ---------------------------------------------------------------------------
-- The public door: four functions, granted to anon.
-- ---------------------------------------------------------------------------

/*
 * What `/f/<slug>` renders. NULL for a slug that is not a form, which the page
 * shows exactly like a deleted one. A form that is not open answers its title
 * and its state and no questions.
 */
create or replace function public.app_public_form(p_slug text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_form public.forms;
  v_state text;
begin
  if p_slug is null or p_slug !~ '^[a-z0-9]{12}$' then
    return null;
  end if;

  select * into v_form from public.forms f where f.slug = p_slug;
  if not found then
    return null;
  end if;

  v_state := public.app_form_state(v_form);
  return pg_catalog.jsonb_build_object(
    'slug', v_form.slug,
    'title', v_form.title,
    'description', v_form.description,
    'audience', v_form.audience,
    'state', v_state,
    'closes_at', v_form.closes_at,
    'fields', case when v_state = 'closed' then '[]'::jsonb else v_form.fields end
  );
end;
$$;

comment on function public.app_public_form(text) is
  'Public: one form by its slug, for /f/<slug>. Title, description, who may answer, whether it is open, and its questions while it is not closed. NULL for an unknown slug. Never names the linked group or event, the maker or any response.';

/*
 * The identity step. Answers a JSON object and never raises for a wrong
 * identity, because a raise would roll back the row that counts it.
 *
 *   {ok: true, first_name, prefill, masked, already}
 *   {ok: false, reason: 'missing' | 'closed' | 'not_needed' | 'incomplete' | 'no_match' | 'throttled'}
 */
create or replace function public.app_public_form_identify(
  p_slug text,
  p_email text,
  p_external_id text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_form public.forms;
  v_key text;
  v_match uuid;
  v_person public.requesters;
  v_prefill jsonb;
begin
  if p_slug is null or p_slug !~ '^[a-z0-9]{12}$' then
    return pg_catalog.jsonb_build_object('ok', false, 'reason', 'missing');
  end if;
  select * into v_form from public.forms f where f.slug = p_slug;
  if not found then
    return pg_catalog.jsonb_build_object('ok', false, 'reason', 'missing');
  end if;
  if public.app_form_state(v_form) = 'closed' then
    return pg_catalog.jsonb_build_object('ok', false, 'reason', 'closed');
  end if;
  if v_form.audience <> 'directory' then
    return pg_catalog.jsonb_build_object('ok', false, 'reason', 'not_needed');
  end if;
  if pg_catalog.btrim(coalesce(p_email, '')) = '' or pg_catalog.btrim(coalesce(p_external_id, '')) = '' then
    return pg_catalog.jsonb_build_object('ok', false, 'reason', 'incomplete');
  end if;

  v_key := public.app_form_client_key();

  -- The window slides: a day of history is more than the fifteen minutes
  -- counted, and pruning here keeps the table the size of one busy morning.
  delete from public.form_identity_attempts a
  where a.form_id = v_form.id and a.at < pg_catalog.now() - interval '1 day';

  if public.app_form_throttled(v_form.id, v_key, 'miss') then
    return pg_catalog.jsonb_build_object('ok', false, 'reason', 'throttled');
  end if;

  v_match := public.app_form_match_identity(p_email, p_external_id);
  if v_match is null then
    insert into public.form_identity_attempts (form_id, client_key, kind)
    values (v_form.id, v_key, 'miss');
    return pg_catalog.jsonb_build_object('ok', false, 'reason', 'no_match');
  end if;

  select * into v_person from public.requesters r where r.id = v_match;
  v_prefill := public.app_form_prefill(v_form, v_person);

  return pg_catalog.jsonb_build_object(
    'ok', true,
    'first_name', public.app_form_first_name(v_person),
    'prefill', v_prefill -> 'prefill',
    'masked', v_prefill -> 'masked',
    'already', exists (
      select 1 from public.form_responses r
      where r.form_id = v_form.id and r.requester_id = v_person.id
    )
  );
end;
$$;

comment on function public.app_public_form_identify(text, text, text) is
  'Public: the identity step of a directory form. Both the school email and the OSIS or staff id must name the same directory record; a miss is counted against the caller and the form and answered with the same no_match whichever half was wrong. On a match, answers the first name and the directory values for this form''s directory questions only, with a guardian phone masked to its last four digits.';

/*
 * The public submit. Identity is checked again — nothing about the earlier
 * step is trusted — and a closed or full form refuses a new response here, in
 * the database, whatever the page believed.
 *
 *   {ok: true, updated, first_name}
 *   {ok: false, reason: 'missing' | 'closed' | 'full' | 'no_match' | 'throttled'}
 *
 * An answer that does not fit its question raises, with a sentence naming the
 * question: nothing is stored and nothing needs keeping.
 */
create or replace function public.app_public_form_submit(
  p_slug text,
  p_email text,
  p_external_id text,
  p_answers jsonb
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_form public.forms;
  v_state text;
  v_key text;
  v_match uuid;
  v_person public.requesters;
  v_clean jsonb;
  v_result jsonb;
begin
  if p_slug is null or p_slug !~ '^[a-z0-9]{12}$' then
    return pg_catalog.jsonb_build_object('ok', false, 'reason', 'missing');
  end if;
  -- Locked, so two responses arriving together cannot both be the last one
  -- under the cap.
  select * into v_form from public.forms f where f.slug = p_slug for update;
  if not found then
    return pg_catalog.jsonb_build_object('ok', false, 'reason', 'missing');
  end if;

  v_state := public.app_form_state(v_form);
  if v_state = 'closed' then
    return pg_catalog.jsonb_build_object('ok', false, 'reason', 'closed');
  end if;

  v_key := public.app_form_client_key();

  if v_form.audience = 'directory' then
    if public.app_form_throttled(v_form.id, v_key, 'miss') then
      return pg_catalog.jsonb_build_object('ok', false, 'reason', 'throttled');
    end if;
    v_match := public.app_form_match_identity(p_email, p_external_id);
    if v_match is null then
      insert into public.form_identity_attempts (form_id, client_key, kind)
      values (v_form.id, v_key, 'miss');
      return pg_catalog.jsonb_build_object('ok', false, 'reason', 'no_match');
    end if;
    select * into v_person from public.requesters r where r.id = v_match;
  else
    if public.app_form_throttled(v_form.id, v_key, 'submit') then
      return pg_catalog.jsonb_build_object('ok', false, 'reason', 'throttled');
    end if;
  end if;

  -- Full refuses a NEW response. Somebody correcting the one they already
  -- sent is not taking a place.
  if v_state = 'full' and not (
    v_person.id is not null and exists (
      select 1 from public.form_responses r
      where r.form_id = v_form.id and r.requester_id = v_person.id
    )
  ) then
    return pg_catalog.jsonb_build_object('ok', false, 'reason', 'full');
  end if;

  v_clean := public.app_form_clean_answers(v_form, p_answers, v_person);

  if v_form.audience <> 'directory' then
    insert into public.form_identity_attempts (form_id, client_key, kind)
    values (v_form.id, v_key, 'submit');
  end if;

  v_result := public.app_form_record_response(v_form, v_person.id, v_clean, 'link', null);

  return pg_catalog.jsonb_build_object(
    'ok', true,
    'updated', (v_result ->> 'updated')::boolean,
    'first_name', case when v_person.id is not null then public.app_form_first_name(v_person) end
  );
end;
$$;

comment on function public.app_public_form_submit(text, text, text, jsonb) is
  'Public: sends one response to an open form. A directory form re-checks the email and id on every call; an anyone form is throttled per caller and per form. Refuses a closed form, and a full one unless the respondent is replacing their own earlier answers. Adds a matched respondent to the linked group and marks them present at the linked event.';

-- ---------------------------------------------------------------------------
-- Signed-in reads
-- ---------------------------------------------------------------------------

create or replace function public.app_list_forms()
returns table (
  id uuid,
  slug text,
  title text,
  description text,
  state text,
  audience text,
  response_count integer,
  last_response_at timestamptz,
  shared boolean,
  mine boolean,
  owner_name text,
  group_name text,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.app_accounts;
begin
  v_actor := public.app_require_actor();

  return query
    select
      f.id,
      f.slug,
      f.title,
      f.description,
      public.app_form_state(f),
      f.audience,
      (select pg_catalog.count(*)::integer from public.form_responses r where r.form_id = f.id),
      (select pg_catalog.max(r.submitted_at) from public.form_responses r where r.form_id = f.id),
      f.shared,
      f.created_by = v_actor.id,
      a.display_name,
      g.name,
      f.updated_at
    from public.forms f
    left join public.app_accounts a on a.id = f.created_by
    left join public.people_groups g on g.id = f.group_id
    where public.app_form_can_see(f)
    order by f.updated_at desc, f.id;
end;
$$;

comment on function public.app_list_forms() is
  'Every form the caller may see — shared ones and their own — newest change first, each with its state and response count.';

create or replace function public.app_get_form(p_form uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.app_accounts;
  v_form public.forms;
begin
  v_actor := public.app_require_actor();

  select * into v_form from public.forms f where f.id = p_form;
  if not found or not public.app_form_can_see(v_form) then
    return null;
  end if;

  return pg_catalog.jsonb_build_object(
    'id', v_form.id,
    'slug', v_form.slug,
    'title', v_form.title,
    'description', v_form.description,
    'fields', v_form.fields,
    'is_open', v_form.is_open,
    'closes_at', v_form.closes_at,
    'response_cap', v_form.response_cap,
    'audience', v_form.audience,
    'group_id', v_form.group_id,
    'group_name', (select g.name from public.people_groups g where g.id = v_form.group_id),
    'event_id', v_form.event_id,
    'event_name', (select e.name from public.group_events e where e.id = v_form.event_id),
    'event_held_on', (select e.held_on from public.group_events e where e.id = v_form.event_id),
    'shared', v_form.shared,
    'mine', v_form.created_by = v_actor.id,
    'can_own', public.app_form_can_own(v_form),
    'owner_name', (select a.display_name from public.app_accounts a where a.id = v_form.created_by),
    'state', public.app_form_state(v_form),
    'response_count', (select pg_catalog.count(*) from public.form_responses r where r.form_id = v_form.id),
    'created_at', v_form.created_at,
    'updated_at', v_form.updated_at
  );
end;
$$;

comment on function public.app_get_form(uuid) is
  'One form with its questions and settings, or NULL when there is no such form or the caller may not see it.';

/*
 * Every response to one form, newest first, with who answered when they were
 * matched. Refused out loud for a form the caller cannot see, so a screen can
 * tell "no responses yet" from "not yours".
 */
create or replace function public.app_form_responses(p_form uuid)
returns table (
  id uuid,
  requester_id uuid,
  display_name text,
  external_id text,
  answers jsonb,
  changed text[],
  via text,
  submitted_at timestamptz,
  recorded_by_name text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_form public.forms;
begin
  perform public.app_require_actor();

  select * into v_form from public.forms f where f.id = p_form;
  if not found or not public.app_form_can_see(v_form) then
    raise exception 'There is no form with that id.' using errcode = 'check_violation';
  end if;

  return query
    select
      r.id,
      r.requester_id,
      p.display_name,
      p.external_id,
      r.answers,
      r.changed,
      r.via,
      r.submitted_at,
      a.display_name
    from public.form_responses r
    left join public.requesters p on p.id = r.requester_id
    left join public.app_accounts a on a.id = r.recorded_by
    where r.form_id = p_form
    order by r.submitted_at desc, r.id
    limit 5000;
end;
$$;

comment on function public.app_form_responses(uuid) is
  'Every response to one form, newest first, at most 5,000, with the matched person''s name and id. Refuses a form the caller cannot see.';

/* What the command palette finds by title. */
create or replace function public.app_search_forms(p_query text, p_limit integer default 8)
returns table (
  id uuid,
  title text,
  subtitle text,
  meta text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_query text := pg_catalog.btrim(coalesce(p_query, ''));
  v_pattern text;
begin
  perform public.app_require_actor();
  if pg_catalog.length(v_query) < 2 then
    return;
  end if;
  -- LIKE's own wildcards are matched literally.
  v_pattern := '%' || pg_catalog.replace(pg_catalog.replace(pg_catalog.replace(
    pg_catalog.lower(v_query), '\', '\\'), '%', '\%'), '_', '\_') || '%';

  return query
    select
      f.id,
      f.title,
      nullif(pg_catalog.left(f.description, 120), ''),
      (select pg_catalog.count(*)::integer from public.form_responses r where r.form_id = f.id)::text
        || case
             when (select pg_catalog.count(*) from public.form_responses r where r.form_id = f.id) = 1
               then ' response' else ' responses'
           end
    from public.forms f
    where public.app_form_can_see(f)
      and pg_catalog.lower(f.title) like v_pattern
    order by (pg_catalog.lower(f.title) like pg_catalog.lower(v_query) || '%') desc, f.updated_at desc
    limit greatest(1, least(coalesce(p_limit, 8), 25));
end;
$$;

comment on function public.app_search_forms(text, integer) is
  'Forms the caller may see whose title contains the query, titles that start with it first. At most 25.';

-- ---------------------------------------------------------------------------
-- Signed-in writes
-- ---------------------------------------------------------------------------

create or replace function public.app_create_form(
  p_title text,
  p_description text default '',
  p_fields jsonb default '[]'::jsonb,
  p_audience text default 'directory'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.app_accounts;
  v_title text;
  v_fields jsonb;
  v_id uuid;
  v_try integer := 0;
begin
  v_actor := public.app_require_actor();

  v_title := pg_catalog.btrim(coalesce(p_title, ''));
  if v_title = '' then
    raise exception 'Give the form a title.' using errcode = 'check_violation';
  end if;
  if pg_catalog.length(v_title) > 120 then
    raise exception 'A form title is 120 characters at most.' using errcode = 'check_violation';
  end if;
  if coalesce(p_audience, 'directory') not in ('directory', 'anyone') then
    raise exception 'Choose who can answer: directory or anyone.' using errcode = 'check_violation';
  end if;
  v_fields := public.app_form_clean_fields(p_fields);

  -- A collision in 59 bits is not going to happen; if it does, draw again.
  loop
    v_try := v_try + 1;
    begin
      insert into public.forms (slug, title, description, fields, audience, created_by)
      values (
        public.app_form_slug(),
        v_title,
        pg_catalog.left(pg_catalog.btrim(coalesce(p_description, '')), 2000),
        v_fields,
        coalesce(p_audience, 'directory'),
        v_actor.id
      )
      returning id into v_id;
      exit;
    exception
      when unique_violation then
        if v_try >= 5 then
          raise;
        end if;
    end;
  end loop;

  perform public.app_log_record_event('form', v_id, 'form_created', v_actor.id, 'Form created: ' || v_title);
  return v_id;
end;
$$;

comment on function public.app_create_form(text, text, jsonb, text) is
  'Starts a form with a title, a description and optionally its questions. Any active account. Shared with the desk by default; records one history entry.';

create or replace function public.app_save_form(
  p_form uuid,
  p_title text,
  p_description text,
  p_fields jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.app_accounts;
  v_form public.forms;
  v_title text;
  v_description text;
  v_fields jsonb;
begin
  v_actor := public.app_require_actor();

  select * into v_form from public.forms f where f.id = p_form for update;
  if not found or not public.app_form_can_see(v_form) then
    raise exception 'There is no form with that id.' using errcode = 'check_violation';
  end if;

  v_title := pg_catalog.btrim(coalesce(p_title, ''));
  if v_title = '' then
    raise exception 'Give the form a title.' using errcode = 'check_violation';
  end if;
  if pg_catalog.length(v_title) > 120 then
    raise exception 'A form title is 120 characters at most.' using errcode = 'check_violation';
  end if;
  v_description := pg_catalog.left(pg_catalog.btrim(coalesce(p_description, '')), 2000);
  v_fields := public.app_form_clean_fields(p_fields);

  if v_form.title = v_title and v_form.description = v_description and v_form.fields = v_fields then
    return;
  end if;

  update public.forms f
  set title = v_title,
      description = v_description,
      fields = v_fields,
      updated_at = pg_catalog.now()
  where f.id = p_form;
end;
$$;

comment on function public.app_save_form(uuid, text, text, jsonb) is
  'Saves a form''s title, description and questions, as the builder autosaves them. Anybody who can see the form. Saving what is already there writes nothing.';

create or replace function public.app_save_form_settings(
  p_form uuid,
  p_is_open boolean,
  p_closes_at timestamptz,
  p_response_cap integer,
  p_audience text,
  p_group uuid,
  p_event uuid,
  p_shared boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.app_accounts;
  v_form public.forms;
  v_group uuid := p_group;
  v_event_group uuid;
  v_open boolean := coalesce(p_is_open, true);
  v_shared boolean := coalesce(p_shared, true);
begin
  v_actor := public.app_require_actor();

  select * into v_form from public.forms f where f.id = p_form for update;
  if not found or not public.app_form_can_see(v_form) then
    raise exception 'There is no form with that id.' using errcode = 'check_violation';
  end if;

  if coalesce(p_audience, '') not in ('directory', 'anyone') then
    raise exception 'Choose who can answer: directory or anyone.' using errcode = 'check_violation';
  end if;
  if p_response_cap is not null and (p_response_cap < 1 or p_response_cap > 10000) then
    raise exception 'A response limit is between 1 and 10,000.' using errcode = 'check_violation';
  end if;
  if v_shared <> v_form.shared and not public.app_form_can_own(v_form) then
    raise exception 'Only the person who made this form can change who sees it.'
      using errcode = 'insufficient_privilege';
  end if;

  if v_group is not null and not exists (select 1 from public.people_groups g where g.id = v_group) then
    raise exception 'There is no group with that id.' using errcode = 'check_violation';
  end if;
  if p_event is not null then
    select e.group_id into v_event_group from public.group_events e where e.id = p_event;
    if v_event_group is null then
      raise exception 'There is no event with that id.' using errcode = 'check_violation';
    end if;
    -- An event is taken against its own group's roster, so a form that marks
    -- people present also has to put them on that roster.
    if v_group is null then
      v_group := v_event_group;
    elsif v_group <> v_event_group then
      raise exception 'That event belongs to a different group.' using errcode = 'check_violation';
    end if;
  end if;

  update public.forms f
  set is_open = v_open,
      closes_at = p_closes_at,
      response_cap = p_response_cap,
      audience = p_audience,
      group_id = v_group,
      event_id = p_event,
      shared = v_shared,
      updated_at = pg_catalog.now()
  where f.id = p_form;

  if v_open <> v_form.is_open then
    perform public.app_log_record_event(
      'form', p_form,
      case when v_open then 'form_opened' else 'form_closed' end,
      v_actor.id,
      case when v_open then 'Form opened: ' else 'Form closed: ' end || v_form.title
    );
  end if;
end;
$$;

comment on function public.app_save_form_settings(uuid, boolean, timestamptz, integer, text, uuid, uuid, boolean) is
  'Saves whether a form takes responses, when it closes, how many it takes, who may answer, the group it fills and the event it marks. Anybody who can see the form; only its maker or an administrator may change whether it is shared. An event implies its own group, and a different group is refused.';

create or replace function public.app_set_form_open(p_form uuid, p_open boolean)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.app_accounts;
  v_form public.forms;
  v_open boolean := coalesce(p_open, false);
begin
  v_actor := public.app_require_actor();

  select * into v_form from public.forms f where f.id = p_form for update;
  if not found or not public.app_form_can_see(v_form) then
    raise exception 'There is no form with that id.' using errcode = 'check_violation';
  end if;

  if v_form.is_open = v_open then
    return;
  end if;

  update public.forms f
  set is_open = v_open,
      -- Reopening a form whose closing date has passed would reopen nothing,
      -- so the date goes with the switch.
      closes_at = case when v_open and f.closes_at <= pg_catalog.now() then null else f.closes_at end,
      updated_at = pg_catalog.now()
  where f.id = p_form;

  perform public.app_log_record_event(
    'form', p_form,
    case when v_open then 'form_opened' else 'form_closed' end,
    v_actor.id,
    case when v_open then 'Form opened: ' else 'Form closed: ' end || v_form.title
  );
end;
$$;

comment on function public.app_set_form_open(uuid, boolean) is
  'Opens or closes a form to new responses. Reopening clears a closing date that has already passed. Records one history entry.';

create or replace function public.app_delete_form(p_form uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.app_accounts;
  v_form public.forms;
  v_count integer;
begin
  v_actor := public.app_require_actor();

  select * into v_form from public.forms f where f.id = p_form for update;
  if not found or not public.app_form_can_see(v_form) then
    raise exception 'There is no form with that id.' using errcode = 'check_violation';
  end if;
  if not public.app_form_can_own(v_form) then
    raise exception 'Only the person who made this form or an administrator can delete it.'
      using errcode = 'insufficient_privilege';
  end if;

  select pg_catalog.count(*)::integer into v_count from public.form_responses r where r.form_id = p_form;
  delete from public.forms f where f.id = p_form;

  perform public.app_log_record_event(
    'form', p_form, 'form_deleted', v_actor.id,
    'Form deleted: ' || v_form.title,
    v_count || (case when v_count = 1 then ' response' else ' responses' end) || ' went with it.'
  );
end;
$$;

comment on function public.app_delete_form(uuid) is
  'Deletes a form and every response to it. Its maker or an administrator. Records one history entry with the count, never who answered.';

create or replace function public.app_delete_form_response(p_response uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.app_accounts;
  v_form public.forms;
begin
  v_actor := public.app_require_actor();

  select f.* into v_form
  from public.form_responses r
  join public.forms f on f.id = r.form_id
  where r.id = p_response;
  if not found or not public.app_form_can_see(v_form) then
    raise exception 'There is no response with that id.' using errcode = 'check_violation';
  end if;

  delete from public.form_responses r where r.id = p_response;

  -- The roster and the register it filled are left alone: taking somebody off
  -- a trip is its own decision, made on the group's page.
  perform public.app_log_record_event(
    'form', v_form.id, 'form_response_deleted', v_actor.id,
    'Response deleted from ' || v_form.title
  );
end;
$$;

comment on function public.app_delete_form_response(uuid) is
  'Deletes one response. Anybody who can see the form. Leaves the linked roster and register as they are. Records one history entry naming the form and nobody else.';

create or replace function public.app_log_form_export(p_form uuid, p_what text, p_count integer)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.app_accounts;
  v_form public.forms;
  v_count integer := greatest(coalesce(p_count, 0), 0);
begin
  v_actor := public.app_require_actor();
  if coalesce(p_what, '') not in ('csv', 'copy') then
    raise exception 'Say which export: csv or copy.' using errcode = 'check_violation';
  end if;
  select * into v_form from public.forms f where f.id = p_form;
  if not found or not public.app_form_can_see(v_form) then
    raise exception 'There is no form with that id.' using errcode = 'check_violation';
  end if;

  perform public.app_log_record_event(
    'form', p_form,
    case when p_what = 'csv' then 'form_export' else 'form_copy' end,
    v_actor.id,
    pg_catalog.format(
      '%s %s %s from %s.',
      case when p_what = 'csv' then 'Exported' else 'Copied' end,
      v_count,
      case when v_count = 1 then 'response' else 'responses' end,
      v_form.title
    )
  );
end;
$$;

comment on function public.app_log_form_export(uuid, text, integer) is
  'Records that the caller exported or copied a form''s responses, with how many. The content is never written to the log.';

-- ---------------------------------------------------------------------------
-- The kiosk: a signed-in device at a door.
--
-- The account holding the device vouches for the lookup, so an id or an email
-- alone is enough — the same matching rules as app_mark_attendance_by_key.
-- ---------------------------------------------------------------------------

create or replace function public.app_form_kiosk_identify(p_form uuid, p_key text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.app_accounts;
  v_form public.forms;
  v_key text;
  v_count integer;
  v_id uuid;
  v_person public.requesters;
  v_prefill jsonb;
begin
  v_actor := public.app_require_actor();

  select * into v_form from public.forms f where f.id = p_form;
  if not found or not public.app_form_can_see(v_form) then
    raise exception 'There is no form with that id.' using errcode = 'check_violation';
  end if;
  if public.app_form_state(v_form) = 'closed' then
    return pg_catalog.jsonb_build_object('outcome', 'closed');
  end if;

  v_key := pg_catalog.btrim(coalesce(p_key, ''));
  if v_key = '' then
    raise exception 'Scan a card, or type an OSIS, staff id or name.' using errcode = 'check_violation';
  end if;

  with hits as (
    select
      r.id,
      case
        when pg_catalog.lower(coalesce(r.external_id, '')) = pg_catalog.lower(v_key) then 1
        when r.email is not null and pg_catalog.lower(r.email) = pg_catalog.lower(v_key) then 1
        else 2
      end as rank
    from public.requesters r
    where r.kind in ('staff', 'student')
      and (
        pg_catalog.lower(coalesce(r.external_id, '')) = pg_catalog.lower(v_key)
        or (r.email is not null and pg_catalog.lower(r.email) = pg_catalog.lower(v_key))
        or pg_catalog.lower(r.display_name) = pg_catalog.lower(v_key)
      )
  ),
  best as (select pg_catalog.min(h.rank) as rank from hits h)
  select pg_catalog.count(*)::integer, (pg_catalog.array_agg(h.id))[1]
  into v_count, v_id
  from hits h
  join best b on b.rank = h.rank;

  if coalesce(v_count, 0) = 0 then
    return pg_catalog.jsonb_build_object('outcome', 'no_match');
  end if;
  if v_count > 1 then
    return pg_catalog.jsonb_build_object('outcome', 'ambiguous');
  end if;

  select * into v_person from public.requesters r where r.id = v_id;
  v_prefill := public.app_form_prefill(v_form, v_person);

  return pg_catalog.jsonb_build_object(
    'outcome', 'match',
    'requester_id', v_person.id,
    'first_name', public.app_form_first_name(v_person),
    'prefill', v_prefill -> 'prefill',
    'masked', v_prefill -> 'masked',
    'already', exists (
      select 1 from public.form_responses r
      where r.form_id = v_form.id and r.requester_id = v_person.id
    )
  );
end;
$$;

comment on function public.app_form_kiosk_identify(uuid, text) is
  'Kiosk: finds the person a scanned card or typed OSIS, staff id, email or full name names, and answers their prefill for this form with the guardian phone masked. outcome is match, no_match, ambiguous or closed.';

create or replace function public.app_form_kiosk_submit(p_form uuid, p_requester uuid, p_answers jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor public.app_accounts;
  v_form public.forms;
  v_state text;
  v_person public.requesters;
  v_clean jsonb;
  v_result jsonb;
begin
  v_actor := public.app_require_actor();

  select * into v_form from public.forms f where f.id = p_form for update;
  if not found or not public.app_form_can_see(v_form) then
    raise exception 'There is no form with that id.' using errcode = 'check_violation';
  end if;

  v_state := public.app_form_state(v_form);
  if v_state = 'closed' then
    raise exception 'This form is closed.' using errcode = 'check_violation';
  end if;

  if p_requester is not null then
    select * into v_person from public.requesters r where r.id = p_requester;
    if not found then
      raise exception 'That person is not in the directory.' using errcode = 'check_violation';
    end if;
  elsif v_form.audience = 'directory' then
    raise exception 'Scan an ID first.' using errcode = 'check_violation';
  end if;

  if v_state = 'full' and not (
    v_person.id is not null and exists (
      select 1 from public.form_responses r
      where r.form_id = v_form.id and r.requester_id = v_person.id
    )
  ) then
    raise exception 'This form has all the responses it takes.' using errcode = 'check_violation';
  end if;

  v_clean := public.app_form_clean_answers(v_form, p_answers, v_person);
  v_result := public.app_form_record_response(v_form, v_person.id, v_clean, 'kiosk', v_actor.id);

  return pg_catalog.jsonb_build_object(
    'id', v_result -> 'id',
    'updated', (v_result ->> 'updated')::boolean,
    'first_name', case when v_person.id is not null then public.app_form_first_name(v_person) end
  );
end;
$$;

comment on function public.app_form_kiosk_submit(uuid, uuid, jsonb) is
  'Kiosk: records one response on behalf of the person the kiosk identified, attributed to the signed-in account. Same checks as the public submit, the same linked group and event.';

-- ---------------------------------------------------------------------------
-- The audit screen learns to name a form.
--
-- The body is the definition from `20260916130300_m5_group_events.sql`,
-- restated whole because `create or replace` replaces the whole body, with ONE
-- branch added.
-- ---------------------------------------------------------------------------

create or replace function public.app_audit_log(
  p_actor uuid default null,
  p_via text default null,
  p_kind text default null,
  p_entity text default null,
  p_from timestamptz default null,
  p_to timestamptz default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  source text,
  id uuid,
  at timestamptz,
  actor_id uuid,
  actor_name text,
  performed_via text,
  ai_model text,
  kind text,
  entity_type text,
  entity_id uuid,
  entity_label text,
  summary text,
  detail text,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.app_is_admin() then
    raise exception 'Only an administrator can read the audit log.'
      using errcode = 'insufficient_privilege';
  end if;

  return query
    with combined as (
      select
        'activity'::text as source,
        e.id,
        e.at,
        e.actor_id,
        e.performed_via,
        e.ai_model,
        e.kind,
        'ticket'::text as entity_type,
        e.ticket_id as entity_id,
        t.number as entity_label,
        e.summary,
        e.detail
      from public.activity_events e
      join public.tickets t on t.id = e.ticket_id

      union all

      select
        'account'::text,
        e.id,
        e.at,
        e.actor_id,
        'user'::text,
        null::text,
        e.kind,
        'account'::text,
        e.account_id,
        a.display_name,
        pg_catalog.initcap(pg_catalog.replace(e.kind, '_', ' ')),
        e.detail
      from public.account_events e
      join public.app_accounts a on a.id = e.account_id

      union all

      select
        'record'::text,
        e.id,
        e.at,
        e.actor_id,
        e.performed_via,
        e.ai_model,
        e.kind,
        e.entity_type,
        e.entity_id,
        case e.entity_type
          when 'requester' then (
            select r.display_name from public.requesters r where r.id = e.entity_id
          )
          when 'inventory_device' then (
            select coalesce(
              nullif(pg_catalog.btrim(coalesce(d.asset_tag, '')), ''),
              nullif(pg_catalog.btrim(coalesce(d.serial_number, '')), ''),
              d.external_id
            )
            from public.inventory_devices d where d.id = e.entity_id
          )
          when 'invite' then (
            select i.email from public.account_invites i where i.id = e.entity_id
          )
          when 'group' then (
            select g.name from public.people_groups g where g.id = e.entity_id
          )
          -- A form is known by its title. One that has been deleted reads as
          -- "(deleted)", like any other record that is gone.
          when 'form' then (
            select f.title from public.forms f where f.id = e.entity_id
          )
          when 'account' then (
            select a.display_name from public.app_accounts a where a.id = e.entity_id
          )
        end,
        e.summary,
        e.detail
      from public.record_events e
    ),
    filtered as (
      select c.*
      from combined c
      where (p_actor is null or c.actor_id = p_actor)
        and (p_via is null or c.performed_via = p_via)
        and (p_kind is null or c.kind = p_kind)
        and (p_entity is null or c.entity_type = p_entity)
        and (p_from is null or c.at >= p_from)
        and (p_to is null or c.at <= p_to)
    )
    select
      f.source, f.id, f.at, f.actor_id,
      act.display_name,
      f.performed_via, f.ai_model, f.kind, f.entity_type, f.entity_id,
      f.entity_label, f.summary, f.detail,
      pg_catalog.count(*) over () as total_count
    from filtered f
    left join public.app_accounts act on act.id = f.actor_id
    order by f.at desc, f.id
    limit greatest(0, least(coalesce(p_limit, 50), 200))
    offset greatest(0, coalesce(p_offset, 0));
end;
$$;

-- ---------------------------------------------------------------------------
-- Row-level security and grants
-- ---------------------------------------------------------------------------

alter table public.forms enable row level security;
alter table public.form_responses enable row level security;
alter table public.form_identity_attempts enable row level security;

drop policy if exists forms_select_visible on public.forms;
drop policy if exists form_responses_select_visible on public.form_responses;

-- Inline rather than through app_form_can_see(), so the policy needs no grant
-- beyond the two helpers every other policy here already uses.
create policy forms_select_visible
  on public.forms for select to authenticated
  using (
    public.app_active_account_id() is not null
    and (shared or created_by = public.app_active_account_id() or public.app_is_admin())
  );

create policy form_responses_select_visible
  on public.form_responses for select to authenticated
  using (
    exists (
      select 1 from public.forms f
      where f.id = form_responses.form_id
        and public.app_active_account_id() is not null
        and (f.shared or f.created_by = public.app_active_account_id() or public.app_is_admin())
    )
  );

-- form_identity_attempts carries no policy at all: RLS on and nothing
-- granted, so no client role can read or write it.

revoke all on table
  public.forms,
  public.form_responses,
  public.form_identity_attempts
from public, anon, authenticated;

grant select on table public.forms, public.form_responses to authenticated;

revoke execute on function
  public.app_form_slug(),
  public.app_form_can_see(public.forms),
  public.app_form_can_own(public.forms),
  public.app_form_state(public.forms),
  public.app_form_clean_fields(jsonb),
  public.app_form_directory_value(public.requesters, text),
  public.app_form_prefill(public.forms, public.requesters),
  public.app_form_first_name(public.requesters),
  public.app_form_clean_answers(public.forms, jsonb, public.requesters),
  public.app_form_record_response(public.forms, uuid, jsonb, text, uuid),
  public.app_form_client_key(),
  public.app_form_throttled(uuid, text, text),
  public.app_form_match_identity(text, text)
from public, anon, authenticated;

revoke execute on function
  public.app_public_form(text),
  public.app_public_form_identify(text, text, text),
  public.app_public_form_submit(text, text, text, jsonb),
  public.app_list_forms(),
  public.app_get_form(uuid),
  public.app_form_responses(uuid),
  public.app_search_forms(text, integer),
  public.app_create_form(text, text, jsonb, text),
  public.app_save_form(uuid, text, text, jsonb),
  public.app_save_form_settings(uuid, boolean, timestamptz, integer, text, uuid, uuid, boolean),
  public.app_set_form_open(uuid, boolean),
  public.app_delete_form(uuid),
  public.app_delete_form_response(uuid),
  public.app_log_form_export(uuid, text, integer),
  public.app_form_kiosk_identify(uuid, text),
  public.app_form_kiosk_submit(uuid, uuid, jsonb)
from public, anon;

-- The public door. These three and nothing else.
grant execute on function
  public.app_public_form(text),
  public.app_public_form_identify(text, text, text),
  public.app_public_form_submit(text, text, text, jsonb)
to anon, authenticated;

grant execute on function
  public.app_list_forms(),
  public.app_get_form(uuid),
  public.app_form_responses(uuid),
  public.app_search_forms(text, integer),
  public.app_create_form(text, text, jsonb, text),
  public.app_save_form(uuid, text, text, jsonb),
  public.app_save_form_settings(uuid, boolean, timestamptz, integer, text, uuid, uuid, boolean),
  public.app_set_form_open(uuid, boolean),
  public.app_delete_form(uuid),
  public.app_delete_form_response(uuid),
  public.app_log_form_export(uuid, text, integer),
  public.app_form_kiosk_identify(uuid, text),
  public.app_form_kiosk_submit(uuid, uuid, jsonb)
to authenticated;
