/**
 * Local-only guard and connection discovery for the database test suite.
 *
 * Two hard rules enforced here:
 *   1. The suite FAILS (never skips, never passes) when the local database is
 *      not running. A green run must mean the checks actually executed.
 *   2. The suite refuses to run against anything that is not a local stack. It
 *      reads the live connection details from the Supabase CLI, then rejects any
 *      host that is not loopback, and rejects a workspace that has been linked
 *      to a hosted project. No remote project can be reset or written to by
 *      running these tests.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const PROJECT_ROOT = path.resolve(HERE, '..', '..', '..');

/** Docker Desktop ships its credential helper outside the default PATH. */
const EXTRA_PATHS = [
  '/Applications/Docker.app/Contents/Resources/bin',
  '/usr/local/bin',
  '/opt/homebrew/bin',
];

function commandEnv(): NodeJS.ProcessEnv {
  const extras = EXTRA_PATHS.filter((entry) => existsSync(entry));
  return { ...process.env, PATH: [...extras, process.env.PATH ?? ''].join(path.delimiter) };
}

export interface LocalStack {
  apiUrl: string;
  anonKey: string;
  serviceRoleKey: string;
}

function fail(message: string): never {
  throw new Error(
    `${message}\n\n` +
      'Start the local database first:\n' +
      '  npm run db:start\n' +
      'Then re-run:\n' +
      '  npm run test:db\n',
  );
}

/** Rejects any workspace that has been linked to a hosted Supabase project. */
function assertNotLinked(): void {
  const tempDir = path.join(PROJECT_ROOT, 'supabase', '.temp');
  if (!existsSync(tempDir)) return;
  const linkMarkers = ['project-ref', 'remote-db-url', 'pooler-url'];
  const present = readdirSync(tempDir).filter((entry) => linkMarkers.includes(entry));
  if (present.length > 0) {
    throw new Error(
      `Refusing to run: this workspace looks linked to a hosted Supabase project ` +
        `(supabase/.temp/${present.join(', ')}). The M2 suite is local-only and must ` +
        `never reset or write to a hosted project. Run "npx supabase unlink" first.`,
    );
  }
}

function assertLoopback(rawUrl: string): void {
  let url: URL;
  try {
    url = new URL(rawUrl);
  } catch {
    throw new Error(`Refusing to run: unparseable API URL "${rawUrl}".`);
  }
  const allowed = new Set(['127.0.0.1', 'localhost', '::1', '[::1]']);
  if (!allowed.has(url.hostname)) {
    throw new Error(
      `Refusing to run against non-local host "${url.hostname}". ` +
        'The M2 database suite only ever targets a local Supabase stack.',
    );
  }
}

let cached: LocalStack | null = null;

/** Reads live local connection details from the CLI. Throws if unavailable. */
export function resolveLocalStack(): LocalStack {
  if (cached) return cached;
  assertNotLinked();

  let raw: string;
  try {
    raw = execFileSync('npx', ['--no-install', 'supabase', 'status', '-o', 'json'], {
      cwd: PROJECT_ROOT,
      env: commandEnv(),
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
      timeout: 120_000,
    });
  } catch (error) {
    const detail = error instanceof Error ? error.message.split('\n')[0] : String(error);
    fail(`The local Supabase stack is not reachable (${detail}).`);
  }

  let status: Record<string, string>;
  try {
    status = JSON.parse(raw) as Record<string, string>;
  } catch {
    fail('Could not parse "supabase status -o json" output.');
  }

  const apiUrl = status.API_URL;
  const anonKey = status.ANON_KEY;
  const serviceRoleKey = status.SERVICE_ROLE_KEY;
  if (!apiUrl || !anonKey || !serviceRoleKey) {
    fail('The local Supabase stack reported no API URL or keys.');
  }

  assertLoopback(apiUrl);

  // Local development keys are generated by the CLI and are identical on every
  // local install. They are read at run time and never written to a file.
  cached = { apiUrl, anonKey, serviceRoleKey };
  return cached;
}

/** Verifies the database actually answers, so an unreachable stack fails loudly. */
export async function assertDatabaseReachable(stack: LocalStack): Promise<void> {
  const response = await fetch(`${stack.apiUrl}/rest/v1/`, {
    headers: { apikey: stack.anonKey },
  }).catch((error: unknown) => {
    fail(`The local Supabase API did not respond (${String(error)}).`);
  });
  if (!response.ok && response.status !== 404) {
    fail(`The local Supabase API responded with HTTP ${response.status}.`);
  }
}
